language: node_js
os:
- linux
- osx
node_js:
- '10'
- '12'
dist: bionic
osx_image: xcode12
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+/
env:
- DEBUG="electron-installer-redhat"
addons:
  apt:
    packages:
    - rpm
  homebrew:
    packages:
    - rpm
deploy:
  provider: npm
  email: unindented@gmail.com
  api_key:
    secure: inExPQpMztnZ8fn72VvxVYyg3BejPbUXQNVp9LRmhvW+eprcoV5frW0/HYP7qJGOzai4xChqeJJf3NEM4bZCjYXKewp9DeQMkM0so9lXtOP2IIcmD50cZkCqSIRsillDMQmpioTVPO7gBoAx/oEv6SekS1U1KLd93rJhVAtJ00coNU9QxEBVV9fEpVGFoHaCz5oYZbyKC7xA8I4LalVbEvfJN48N1wAvHdKFcxhkhExBiFVWgHMr1JoDEGqMDHKKVsnFVS3tvVL0wQ8FFDUGrisB8IoX7mPMtoQPWJMUp+t7Rc1H1PjK+wycIXWpVY8kZ0Jx6EeYWjsEK7BEvYX+8Gw4SVB7r/gfkvCBh/Usa+XxAMCPvxvnIWE2rvsI/vbs6JmlLshQEA1nA9YNMiCf9s9od9RKpyApxFdg1Crks+Za+fbpjjlmT4YP6KeuQV8ETOaImw4cQR5A4taj6XMpdKNKUFp6HNm6rFJwykFkp64Uc+BHCwelba624Ua4cinuMKSGFY/6lQZfwTAJHuBG5sBpBvpNMe5krM2m6c0mfNma1KExtc073Gj5QZBGkWIRCmJrE6HiP+NOGAy9VkTqCg9BQr16dMGogUJwY4+fviaJ4F3+vFSesqnbSSIN1QZaUPi/Y/9hW1wnw58KQWU4YD+MZLzFp/L1Zjm47zOEza4=
  on:
    tags: true
