name: CI

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Install macOS dependencies
        if: matrix.os == 'macos-latest'
        run: brew install rpm
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install
        run: |
          npm install --engine-strict
          npm update
      - name: Test
        run: npm test
        env:
          DEBUG: 'electron-installer-redhat'
